---
title: "house_senate_viz"
author: "Nuo Wen Lei"
date: "7/22/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```

## Party donation over the years


```{r clean-data, echo = FALSE}
house_senate_data = read_csv("data/house_senate.csv")

clean_data = house_senate_data %>% 
  pivot_longer(cols = -year, names_to = "position", values_to = "seats") %>% 
  mutate(
    party = gsub("\\_.*", "", position),
    pos_type = gsub(".*\\_", "", substr(position, 1, nchar(position)-2))
  ) %>% 
  group_by(pos_type, year) %>% 
  summarize(party = party,
            seat_total = seats,
            seats = seats / sum(seats),
            .groups = "drop")
clean_data
```

```{r donation-plot, echo = FALSE}
ggplot(clean_data, aes(x = year, y = seats, color = party)) + 
  facet_wrap(~pos_type) +
  geom_line() + 
  scale_color_manual(
    values = c("blue", "red")
  ) +
  ylim(c(0.25, .75))
```




```{r hist-plot, echo = FALSE}
ggplot(clean_data, aes(x = seat_total)) +
  facet_wrap(~pos_type) + 
  geom_histogram(bins = 8)
```





```{r calc-change, echo = FALSE}
unique_years = clean_data$year %>% unique()
unique_types = clean_data$pos_type %>% unique()

new_tbl = tibble(
  year = numeric(),
  pos_type = character(),
  seat_change_dem = numeric()
)


for (i in seq_along(1:(length(unique_years) - 1))){
  next_year = clean_data %>% filter(year == unique_years[[i+1]], party == "democratic")
  curr_year = clean_data %>% filter(year == unique_years[[i]], party == "democratic")
  for (j in unique_types){
    seat_change = (next_year %>% filter(pos_type == j) %>% pull(seats))[[1]] - (curr_year %>% filter(pos_type == j) %>% pull(seats))[[1]]
    new_tbl = rbind(new_tbl, c(year = unique_years[[i+1]], pos_type = j, seat_change_dem = seat_change))
  }
  
}
colnames(new_tbl) = c("year", "pos_type", "seat_change_dem")

new_tbl = new_tbl %>% 
  mutate(
    year = parse_number(year),
    seat_change_dem = parse_number(seat_change_dem)
  )


new_tbl

```


```{r change-plot, echo = FALSE}
ggplot(new_tbl, aes(x = year, y = seat_change_dem, color = pos_type)) +
  geom_line()
```