---
title: "R Notebook"
output: html_notebook
---
```{r setup, include = FALSE}
library(sjPlot)
library(sjmisc)
library(tidyverse)
```


```{r load-house_senate, echo = FALSE, warning = FALSE, message = FALSEE}
house_senate_data = read_csv("data/house_senate.csv")

house_senate_clean_data = house_senate_data %>% 
  pivot_longer(cols = -year, names_to = "position", values_to = "seats") %>% 
  mutate(
    party = gsub("\\_.*", "", position),
    pos_type = gsub(".*\\_", "", substr(position, 1, nchar(position)-2))
  ) %>% 
  group_by(pos_type, year) %>% 
  summarize(party = party,
            seat_total = seats,
            seats = seats / sum(seats),
            .groups = "drop")
print(house_senate_clean_data %>% colnames())
```

```{r}
leadership_data = read_csv("data/leadership_pac_data/clean_data.csv")

leadership_data %>%
    select(dem, repub, year) %>% 
    rename(
        "Donation to Democrats" = dem,
        "Donation to Republicans" = repub
    ) %>% descr(out = "viewer", show = c("n", "mean", "sd", "range"))


```


```{r}
foreign_data = read_csv("data/foreign_pac_data/clean_data.csv")

foreign_data %>%
    select(dems_sum, repubs_sum, year) %>% 
    rename(
        "Donation to Democrats" = dems_sum,
        "Donation to Republicans" = repubs_sum
    ) %>% descr(out = "viewer", show = c("n", "mean", "sd", "range"))


```

```{r load-industry, echo = FALSE, warning = FALSE, message = FALSE}
industry_data = read_csv("data/industry_donation_data/clean_data.csv")

industry_clean_data = industry_data %>% 
  mutate(dem_percent = dem / total,
         repub_percent = repub / total)

```


```{r}
top_house_industries = c("Dairy",
                         "Vegetables, fruits and tree nut",
                         "Air Transport",
                         "Energy & Natural Resources",
                         "Building Materials & Equipment")
ind1_h = industry_clean_data %>%
    filter(industry_name == "Dairy") %>%
    pull(dem_percent)

ind2_h = industry_clean_data %>%
    filter(industry_name == "Vegetables, fruits and tree nut") %>%
    pull(dem_percent)

ind3_h = industry_clean_data %>%
    filter(industry_name == "Air Transport") %>%
    pull(dem_percent)

ind4_h = industry_clean_data %>%
    filter(industry_name == "Energy & Natural Resources") %>%
    pull(dem_percent)

ind5_h = industry_clean_data %>%
    filter(industry_name == "Building Materials & Equipment") %>%
    pull(dem_percent)

curr_gov = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats)
fit1_h = lm(curr_gov~ind1_h)
fit2_h = lm(curr_gov~ind2_h)
fit3_h = lm(curr_gov~ind3_h)
fit4_h = lm(curr_gov~ind4_h)
fit5_h = lm(curr_gov~ind5_h)

tab_model(fit1_h, fit2_h, fit3_h, fit4_h, fit5_h, show.ci = FALSE)
```

```{r}
top_senate_industries = c(
  "Lobbyists",
  "Savings & Loans",
  "Business Services",
  "Telecom Services",
  "Forestry & Forest Products"
)
ind1_s = industry_clean_data %>%
    filter(industry_name == "Lobbyists") %>%
    pull(dem_percent)

ind2_s = industry_clean_data %>%
    filter(industry_name == "Savings & Loans") %>%
    pull(dem_percent)

ind3_s = industry_clean_data %>%
    filter(industry_name == "Business Services") %>%
    pull(dem_percent)

ind4_s = industry_clean_data %>%
    filter(industry_name == "Telecom Services") %>%
    pull(dem_percent)

ind5_s = industry_clean_data %>%
    filter(industry_name == "Forestry & Forest Products") %>%
    pull(dem_percent)

curr_gov = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats)
fit1_s = lm(curr_gov~ind1_s)
fit2_s = lm(curr_gov~ind2_s)
fit3_s = lm(curr_gov~ind3_s)
fit4_s = lm(curr_gov~ind4_s)
fit5_s = lm(curr_gov~ind5_s)

tab_model(fit1_s, fit2_s, fit3_s, fit4_s, fit5_s, show.ci = FALSE)
```

```{r}
tab_model(fit1_h, fit2_h, fit3_h, fit4_h, fit5_h,
          fit1_s, fit2_s, fit3_s, fit4_s, fit5_s,
          show.ci = FALSE)
```

```{r echo = FALSE, warning = FALSE, message = FALSE}
country_count_tbl = table(foreign_data$country)

count_tibble = tibble(
  name = names(country_count_tbl),
  value = c(country_count_tbl)
)

full_use_ctys = count_tibble %>%
  filter(value == max(value)) %>%
  pull(name)

foreign_percent_data = foreign_data %>% 
  mutate(total = dems_sum + repubs_sum,
         dem_percent = dems_sum / total, 
         repub_percent = repubs_sum / total)
```

```{r}
top_house_countries = c(
  "France",
  "UK",
  "Netherlands",
  "Canada",
  "Germany"
)
cty1_h = foreign_percent_data %>%
    filter(country == "France") %>%
    pull(dem_percent)

cty2_h = foreign_percent_data %>%
    filter(country == "UK") %>%
    pull(dem_percent)

cty3_h = foreign_percent_data %>%
    filter(country == "Netherlands") %>%
    pull(dem_percent)

cty4_h = foreign_percent_data %>%
    filter(country == "Canada") %>%
    pull(dem_percent)

cty5_h = foreign_percent_data %>%
    filter(country == "Germany") %>%
    pull(dem_percent)

curr_gov = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats)
fit1_h = lm(curr_gov~cty1_h)
fit2_h = lm(curr_gov~cty2_h)
fit3_h = lm(curr_gov~cty3_h)
fit4_h = lm(curr_gov~cty4_h)
fit5_h = lm(curr_gov~cty5_h)

tab_model(fit1_h, fit2_h, fit3_h, fit4_h, fit5_h, show.ci = FALSE)
```

```{r}
top_senate_countries = c(
  "UK",
  "France",
  "Denmark",
  "Switzerland",
  "Germany"
)

cty1_s = foreign_percent_data %>%
    filter(country == "UK") %>%
    pull(dem_percent)

cty2_s = foreign_percent_data %>%
    filter(country == "France") %>%
    pull(dem_percent)

cty3_s = foreign_percent_data %>%
    filter(country == "Denmark") %>%
    pull(dem_percent)

cty4_s = foreign_percent_data %>%
    filter(country == "Switzerland") %>%
    pull(dem_percent)

cty5_s = foreign_percent_data %>%
    filter(country == "Germany") %>%
    pull(dem_percent)

curr_gov = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats)
fit1_s = lm(curr_gov~cty2_h)
fit2_s = lm(curr_gov~cty1_h)
fit3_s = lm(curr_gov~cty3_s)
fit4_s = lm(curr_gov~cty4_s)
fit5_s = lm(curr_gov~cty5_h)

tab_model(fit1_s, fit2_s, fit3_s, fit4_s, fit5_s, show.ci = FALSE)
```

```{r}
tab_model(fit1_h, fit2_h, fit3_h, fit4_h, fit5_h,
          fit1_s, fit2_s, fit3_s, fit4_s, fit5_s,
          show.ci = FALSE)
```


```{r}
industry_transposed_data = tibble(a = c(1:11))
industry_transposed_data[["year"]] = unique(industry_clean_data$year)
for (ind in unique(industry_clean_data$industry_name)){
  curr_ind = industry_clean_data %>%
    filter(industry_name == ind) %>% 
    pull(dem_percent)
  
  if (length(curr_ind) != 11){
    next
  }
  
  industry_transposed_data[[ind]] = curr_ind
}
industry_transposed_data
```

```{r}
country_transposed_data = tibble(a = c(1:11))
country_transposed_data[["year"]] = unique(country_transposed_data$year)
for (cty in unique(foreign_percent_data$country)){
  curr_cty = foreign_percent_data %>%
    filter(country == cty) %>% 
    pull(dem_percent)
  
  if (length(curr_cty) != 11){
    next
  }
  
  country_transposed_data[[cty]] = curr_cty
}
country_transposed_data
```
```{r}
inflation_data = read_csv("data/inflation_data.csv")
inflation_data
```
```{r}
# Use top 5 most donated industries and countries in last decade
industry_inflation_data = industry_clean_data %>%
  mutate(total_inflated = total * (inflation_data %>%
                                     filter(year == year) %>%
                                     pull(amount))[[1]]) %>%
  select(industry_name, total_inflated)

country_inflation_data = foreign_data %>%
  mutate(total_inflated = total_sum * (inflation_data %>%
                                     filter(year == year) %>% 
                                     pull(amount))[[1]]) %>% 
  select(country, total_inflated)
  

top_5_donate_industries = industry_clean_data %>%
  group_by(industry_name) %>%
  summarize(t = sum(total), .groups = "drop") %>%
  arrange(desc(t)) %>%
  slice(1:5) %>%
  pull(industry_name)

top_5_donate_countries = foreign_data %>%
  group_by(country) %>%
  summarize(t = sum(total_sum), .groups = "drop") %>% 
  arrange(desc(t)) %>% 
  slice(1:5) %>% 
  pull(country)

print(top_5_donate_industries)
print(top_5_donate_countries)
```

```{r}
curr_gov = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats)

fit1 = lm(curr_gov~., data = industry_transposed_data %>% select(top_5_donate_industries))

tab_model(fit1, show.ci = FALSE)
```

```{r}
curr_gov = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats)

fit2 = lm(curr_gov~., data = industry_transposed_data %>% select(top_5_donate_industries))

tab_model(fit2, show.ci = FALSE)
```


```{r}
tab_model(fit1, fit2, show.ci = FALSE)
```


```{r}
curr_gov = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats)

fit3 = lm(curr_gov~., data = country_transposed_data %>% select(top_5_donate_countries))

tab_model(fit3, show.ci = FALSE)
```

```{r}
curr_gov = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats)

fit4 = lm(curr_gov~., data = country_transposed_data %>% select(top_5_donate_countries))

tab_model(fit4, show.ci = FALSE)
```

```{r}
tab_model(fit3, fit4, show.ci = FALSE)
```

```{r}
tbl = tibble(
  `Leadership PACs` = leadership_clean_data %>% filter(
    party == "dem_percent") %>%
    pull(amount),
  `Foreign PACs` = foreign_clean_data %>% filter(
    party == "dem_percent") %>% 
    pull(amount)
  )

house = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats)

senate = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats)

fit1 = lm(house~., data = tbl)
fit2 = lm(senate~., data = tbl)

tab_model(fit1, fit2, show.ci = FALSE)

```
