---
title: "mannwhitneyu_test_page"
author: "Nuo Wen Lei"
date: "7/23/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
knitr::opts_chunk$set(echo = TRUE)

alpha = .05
```

```{r load-house_senate, echo = FALSE, message = FALSE, warning = FALSE}
house_senate_data = read_csv("../data/house_senate.csv")

house_senate_clean_data = house_senate_data %>% 
  pivot_longer(cols = -year, names_to = "position", values_to = "seats") %>% 
  mutate(
    party = gsub("\\_.*", "", position),
    pos_type = gsub(".*\\_", "", substr(position, 1, nchar(position)-2))
  ) %>% 
  group_by(pos_type, year) %>% 
  summarize(party = party,
            seat_total = seats,
            seats = seats / sum(seats),
            .groups = "drop")
```

```{r load-leadership, echo = FALSE, message = FALSE, warning = FALSE}
leadership_data = read_csv("../data/leadership_pac_data/clean_data.csv")

leadership_clean_data = leadership_data %>% 
  group_by(year) %>% 
  summarize(total = sum(dem) + sum(repub),
            dem = sum(dem),
            repub = sum(repub),
            .groups = "drop") %>%
  mutate(dem_percent = dem / total,
         repub_percent = repub / total) %>% 
  pivot_longer(
    cols = c(dem_percent, repub_percent),
    names_to = "party",
    values_to = "amount"
  )
```

```{r load-foreign, echo = FALSE, message = FALSE, warning = FALSE}
foreign_data = read_csv("../data/foreign_pac_data/clean_data.csv")

foreign_clean_data = foreign_data %>% 
  group_by(year) %>% 
  summarize(total = sum(dems_sum) + sum(repubs_sum),
            dem = sum(dems_sum),
            repub = sum(repubs_sum),
            .groups = "drop") %>%
  mutate(dem_percent = dem / total,
         repub_percent = repub / total) %>% 
  pivot_longer(
    cols = c(dem_percent, repub_percent),
    names_to = "party",
    values_to = "amount"
  )

```

```{r load-industry, echo = FALSE, message = FALSE, warning = FALSE}
industry_data = read_csv("../data/industry_donation_data/clean_data.csv")

industry_clean_data = industry_data %>% 
  mutate(dem_percent = dem / total,
         repub_percent = repub / total)

```


## Use Mann-Whitney U Test to Compare Each PAC Kind to House Senate

### Leadership PACs

#### House of Representatives

```{r echo = FALSE, message = FALSE, warning = FALSE}
leadership_house_w_test = wilcox.test(
  leadership_clean_data %>%
    filter(party == "dem_percent") %>%
    pull(amount),
  house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats),
    conf.int = TRUE)


sprintf("Wilcox Test Statistic Between Leadership PAC Donations by Party and House of Representatives Party Distribution is %.5f with p-value %.5f", 
        leadership_house_w_test$statistic, 
        leadership_house_w_test$p.value)
```

#### Senate

```{r echo = FALSE, message = FALSE, warning = FALSE}
leadership_senate_w_test = wilcox.test(
  leadership_clean_data %>%
    filter(party == "dem_percent") %>%
    pull(amount),
  house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats),
    conf.int = TRUE)


sprintf("Wilcox Test Statistic Between Leadership PAC Donations by Party and Senate Party Distribution is %.5f with p-value %.5f", 
        leadership_senate_w_test$statistic,
        leadership_senate_w_test$p.value)
```

### Foreign PACs

#### House of Representatives

```{r echo = FALSE, message = FALSE, warning = FALSE}
foreign_house_w_test = wilcox.test(
  foreign_clean_data %>%
    filter(party == "dem_percent") %>%
    pull(amount),
  house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats),
    conf.int = TRUE)


sprintf("Wilcox Test Statistic Between Foreign PAC Donations by Party and House of Representatives Party Distribution is %.5f with p-value %.5f", 
        foreign_house_w_test$statistic,
        foreign_house_w_test$p.value)
```

#### Senate

```{r echo = FALSE, message = FALSE, warning = FALSE}
foreign_senate_w_test = wilcox.test(
  foreign_clean_data %>%
    filter(party == "dem_percent") %>%
    pull(amount),
  house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats),
    conf.int = TRUE)


sprintf("Wilcox Test Statistic Between Foreign PAC Donations by Party and Senate Party Distribution is %.5f with p-value %.5f",
        foreign_senate_w_test$statistic,
        foreign_senate_w_test$p.value)
```

### PACs by Industry

Create a tibble with the ttest, p-value, CI data for each different industry

#### House of Representatives

```{r echo = FALSE, message = FALSE, warning = FALSE}
industry_house_w_tbl = tibble(
  industry_name = character(),
  test_statistic = numeric(),
  p_value = numeric(),
  average_total_donation = numeric(),
  CI.0 = numeric(),
  CI.1 = numeric(),
  CI_reject = character(),
  p_reject = character()
)

unique_industries = industry_clean_data$industry_name %>% unique()

for (ind in unique_industries){
  if (length(industry_clean_data %>%
      filter(industry_name == ind) %>%
      pull(dem_percent)) != length(house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats))){
    next
    }
  curr_test = wilcox.test(
    industry_clean_data %>%
      filter(industry_name == ind) %>%
      pull(dem_percent),
    house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats),
    conf.int = TRUE
  )
  
  industry_house_w_tbl = rbind(industry_house_w_tbl,
                                  c(
                                    industry_name = ind,
                                    test_statistic = curr_test$statistic,
                                    p_value = curr_test$p.value,
                                    average_total_donation = mean(industry_clean_data %>%
      filter(industry_name == ind) %>%
      pull(total)),
                                    CI.0 = curr_test$conf.int[[1]],
                                    CI.1 = curr_test$conf.int[[2]],
                                    CI_reject = if_else(curr_test$conf.int[[1]] < 0 && 0 < curr_test$conf.int[[2]], "null", "alternative")
                                  ,
                                    p_reject = if_else(curr_test$p.value < alpha,
                                                       "alternative",
                                                       "null")))
  
}


colnames(industry_house_w_tbl) = c("industry_name",
                                      "test_statistic",
                                      "p_value",
                                      "average_total_donation",
                                      "CI.0",
                                      "CI.1",
                                      "CI_reject",
                                      "p_reject")

industry_house_w_tbl = industry_house_w_tbl %>% 
  mutate(test_statistic = parse_number(test_statistic),
         p_value = parse_number(p_value),
         average_total_donation = parse_number(average_total_donation),
         CI.0 = parse_number(CI.0),
         CI.1 = parse_number(CI.1))
```


```{r industry-influence-distribution-plot-house, echo = FALSE, message = FALSE, warning = FALSE}
plt = ggplot(industry_house_w_tbl, aes(x = p_value, y = average_total_donation)) +
  geom_point(aes(text = paste0("Industry: ", industry_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = .05)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) +
  ggtitle("Average Industry Donation over p-value")

fig = ggplotly(plt) %>% layout(xaxis = list(range = c(0, alpha)))
fig
```

```{r industry-statistic-distribution-plot-house, echo = FALSE, message = FALSE, warning = FALSE}
plt = ggplot(industry_house_w_tbl, aes(x = p_value, y = test_statistic)) +
  geom_point(aes(text = paste0("Industry: ", industry_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = .05)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) + ggtitle("Mann-Whitney U Test Statistic over p-value")

fig = ggplotly(plt) %>% layout(xaxis = list(range = c(0, alpha)))
fig
```





#### Senate

```{r echo = FALSE, message = FALSE, warning = FALSE}
industry_senate_w_tbl = tibble(
  industry_name = character(),
  test_statistic = numeric(),
  p_value = numeric(),
  average_total_donation = numeric(),
  CI.0 = numeric(),
  CI.1 = numeric(),
  CI_reject = character(),
  p_reject = character()
)

unique_industries = industry_clean_data$industry_name %>% unique()

for (ind in unique_industries){
  if (length(industry_clean_data %>%
      filter(industry_name == ind) %>%
      pull(dem_percent)) != length(house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats))){
    next
    }
  curr_test = wilcox.test(
    industry_clean_data %>%
      filter(industry_name == ind) %>%
      pull(dem_percent),
    house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats),
    conf.int = TRUE
  )
  
  industry_senate_w_tbl = rbind(industry_senate_w_tbl,
                                  c(
                                    industry_name = ind,
                                    test_statistic = curr_test$statistic,
                                    p_value = curr_test$p.value,
                                    average_total_donation = mean(industry_clean_data %>%
      filter(industry_name == ind) %>%
      pull(total)),
                                    CI.0 = curr_test$conf.int[[1]],
                                    CI.1 = curr_test$conf.int[[2]],
                                    CI_reject = if_else(curr_test$conf.int[[1]] < 0 && 0 < curr_test$conf.int[[2]], "null", "alternative")
                                  ,
                                    p_reject = if_else(curr_test$p.value < alpha,
                                                       "alternative",
                                                       "null")))
  
}


colnames(industry_senate_w_tbl) = c("industry_name",
                                      "test_statistic",
                                      "p_value",
                                      "average_total_donation",
                                      "CI.0",
                                      "CI.1",
                                      "CI_reject",
                                      "p_reject")

industry_senate_w_tbl = industry_senate_w_tbl %>% 
  mutate(
         test_statistic = parse_number(test_statistic),
         p_value = parse_number(p_value),
         average_total_donation = parse_number(average_total_donation),
         CI.0 = parse_number(CI.0),
         CI.1 = parse_number(CI.1))
```


```{r industry-influence-distribution-plot-senate, echo = FALSE, message = FALSE, warning = FALSE}
plt = ggplot(industry_senate_w_tbl, aes(x = p_value, y = average_total_donation)) +
  geom_point(aes(text = paste0("Industry: ", industry_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = .05)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) + ggtitle("Average Industry Donation over p-value")

fig = ggplotly(plt) %>% layout(xaxis = list(range = c(0, alpha)))
fig
```

```{r industry-statistic-distribution-plot-senate, echo = FALSE, message = FALSE, warning = FALSE}
plt = ggplot(industry_senate_w_tbl, aes(x = p_value, y = test_statistic)) +
  geom_point(aes(text = paste0("Industry: ", industry_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = .05)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) + ggtitle("Mann-Whitney U Test Statistic over p-value")

fig = ggplotly(plt) %>% layout(xaxis = list(range = c(0, alpha))) 
fig
```



### Foreign PACs by Country

```{r echo = FALSE, warning = FALSE, message = FALSE}
country_count_tbl = table(foreign_data$country)

count_tibble = tibble(
  name = names(country_count_tbl),
  value = c(country_count_tbl)
)

full_use_ctys = count_tibble %>%
  filter(value == max(value)) %>%
  pull(name)

foreign_percent_data = foreign_data %>% 
  mutate(total = dems_sum + repubs_sum,
         dem_percent = dems_sum / total, 
         repub_percent = repubs_sum / total)
```

#### House of Representatives

```{r echo = FALSE, warning = FALSE, message = FALSE}
country_house_w_tbl = tibble(
  country_name = character(),
  test_statistic = numeric(),
  p_value = numeric(),
  average_total_donation = numeric(),
  CI.0 = numeric(),
  CI.1 = numeric(),
  CI_reject = character(),
  p_reject = character()
)

for (cty in full_use_ctys){
  curr_cty_data = foreign_percent_data %>%
    filter(country == cty) %>% 
    pull(dem_percent)
  
  curr_gov_data = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "house") %>% 
    pull(seats)
  
  if (length(curr_cty_data) != length(curr_gov_data)){
    next
  }
  
  curr_test = wilcox.test(
    curr_cty_data,
    curr_gov_data,
    conf.int = TRUE
  )
  
  country_house_w_tbl = rbind(country_house_w_tbl,
                              c(
                                    country_name = cty,
                                    test_statistic = curr_test$statistic,
                                    p_value = curr_test$p.value,
                                    average_total_donation = mean(foreign_percent_data %>%
      filter(country == cty) %>%
      pull(total)),
                                    CI.0 = curr_test$conf.int[[1]],
                                    CI.1 = curr_test$conf.int[[2]],
                                    CI_reject = if_else(curr_test$conf.int[[1]] < 0 && 0 < curr_test$conf.int[[2]], "null", "alternative")
                                  ,
                                    p_reject = if_else(curr_test$p.value < alpha,
                                                       "alternative",
                                                       "null")
      ))
}

colnames(country_house_w_tbl) = c("country_name",
                                      "test_statistic",
                                      "p_value",
                                      "average_total_donation",
                                      "CI.0",
                                      "CI.1",
                                      "CI_reject",
                                      "p_reject")


country_house_w_tbl = country_house_w_tbl %>% 
  mutate(
         test_statistic = parse_number(test_statistic),
         p_value = parse_number(p_value),
         average_total_donation = parse_number(average_total_donation),
         CI.0 = parse_number(CI.0),
         CI.1 = parse_number(CI.1))

```


```{r country-influence-distribution-plot-house, echo = FALSE, message = FALSE, warning = FALSE}
plt = ggplot(country_house_w_tbl, aes(x = p_value, y = average_total_donation)) +
  geom_point(aes(text = paste0("Country: ", country_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = .05)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) +
  ggtitle("Average Country Donation over p-value")

fig = ggplotly(plt) %>% layout(xaxis = list(range = c(0, alpha)))
fig
```

```{r country-statistic-distribution-plot-house, echo = FALSE, message = FALSE, warning = FALSE}
plt = ggplot(country_house_w_tbl, aes(x = p_value, y = test_statistic)) +
  geom_point(aes(text = paste0("Country: ", country_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = .05)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) + ggtitle("Mann-Whitney U Test over p-value")

fig = ggplotly(plt) %>% layout(xaxis = list(range = c(0, alpha)))
fig
```


#### Senate

```{r echo = FALSE, warning = FALSE, message = FALSE}
country_senate_w_tbl = tibble(
  country_name = character(),
  test_statistic = numeric(),
  p_value = numeric(),
  average_total_donation = numeric(),
  CI.0 = numeric(),
  CI.1 = numeric(),
  CI_reject = character(),
  p_reject = character()
)

for (cty in full_use_ctys){
  curr_cty_data = foreign_percent_data %>%
    filter(country == cty) %>% 
    pull(dem_percent)
  
  curr_gov_data = house_senate_clean_data %>% 
    filter(party == "democratic",
           pos_type == "senate") %>% 
    pull(seats)
  
  if (length(curr_cty_data) != length(curr_gov_data)){
    next
  }
  
  curr_test = wilcox.test(
    curr_cty_data,
    curr_gov_data,
    conf.int = TRUE
  )
  
  country_senate_w_tbl = rbind(country_senate_w_tbl,
                              c(
                                    country_name = cty,
                                    test_statistic = curr_test$statistic,
                                    p_value = curr_test$p.value,
                                    average_total_donation = mean(foreign_percent_data %>%
      filter(country == cty) %>%
      pull(total)),
                                    CI.0 = curr_test$conf.int[[1]],
                                    CI.1 = curr_test$conf.int[[2]],
                                    CI_reject = if_else(curr_test$conf.int[[1]] < 0 && 0 < curr_test$conf.int[[2]], "null", "alternative")
                                  ,
                                    p_reject = if_else(curr_test$p.value < alpha,
                                                       "alternative",
                                                       "null")
      ))
}

colnames(country_senate_w_tbl) = c("country_name",
                                      "test_statistic",
                                      "p_value",
                                      "average_total_donation",
                                      "CI.0",
                                      "CI.1",
                                      "CI_reject",
                                      "p_reject")


country_senate_w_tbl = country_senate_w_tbl %>% 
  mutate(
         test_statistic = parse_number(test_statistic),
         p_value = parse_number(p_value),
         average_total_donation = parse_number(average_total_donation),
         CI.0 = parse_number(CI.0),
         CI.1 = parse_number(CI.1))

```


```{r country-influence-distribution-plot-senate, echo = FALSE, message = FALSE, warning = FALSE}
plt = ggplot(country_senate_w_tbl, aes(x = p_value, y = average_total_donation)) +
  geom_point(aes(text = paste0("Country: ", country_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = .05)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) + ggtitle("Average Country Donation over p-value")

fig = ggplotly(plt) %>% layout(xaxis = list(range = c(0, alpha)))
fig
```

```{r country-statistic-distribution-plot-senate, echo = FALSE, message = FALSE, warning = FALSE}
plt = ggplot(country_senate_w_tbl, aes(x = p_value, y = test_statistic)) +
  geom_point(aes(text = paste0("Country: ", country_name))) +
  scale_y_log10() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = .05)) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0)) + ggtitle("Mann-Whitney U Test Statistic over p-value")

fig = ggplotly(plt) %>% layout(xaxis = list(range = c(0, alpha)))
fig
```






















