---
title: "Figure 3"
author: "Nuo Wen Lei"
date: "8/7/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggthemes)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```



```{r party-donation-clean, echo = FALSE}
foreign_data = read_csv("../data/foreign_pac_data/clean_data.csv")

foreign_clean_data = foreign_data %>% 
  group_by(year) %>% 
  summarize(total = sum(dems_sum) + sum(repubs_sum),
            dem = sum(dems_sum),
            repub = sum(repubs_sum),
            .groups = "drop") %>%
  mutate(dem_percent = dem / total,
         repub_percent = repub / total) %>% 
  pivot_longer(
    cols = c(dem_percent, repub_percent),
    names_to = "party",
    values_to = "amount"
  )
```

```{r load-house_senate, echo = FALSE, warning = FALSE, message = FALSE}
house_senate_data = read_csv("../data/house_senate.csv")

house_senate_clean_data = house_senate_data %>% 
  pivot_longer(cols = -year, names_to = "position", values_to = "seats") %>% 
  mutate(
    party = gsub("\\_.*", "", position),
    pos_type = gsub(".*\\_", "", substr(position, 1, nchar(position)-2))
  ) %>% 
  group_by(pos_type, year) %>% 
  summarize(party = party,
            seat_total = seats,
            seats = seats / sum(seats),
            .groups = "drop")
```


```{r}
house_senate_bound = rbind(foreign_clean_data %>% 
  mutate(party = ifelse(party == "dem_percent", "democratic", "republican"),
         pos_type = "donations") %>% 
  rename(
    seats = amount
  ) %>% 
  select(pos_type, year, party, seats),
  house_senate_clean_data %>% 
    select(pos_type, year, party, seats))

```


```{r top-5-countries}
top_5_donate_countries = foreign_data %>%
  group_by(country) %>%
  summarize(t = sum(total_sum), .groups = "drop") %>% 
  arrange(desc(t)) %>% 
  slice(1:5) %>% 
  pull(country)

top_5_foreign_data_bound = rbind(foreign_data %>% 
  filter(country %in% top_5_donate_countries) %>% 
  mutate(
    total = dems_sum + repubs_sum,
    democratic = dems_sum / total,
    republican = repubs_sum / total
  ) %>% 
  rename(
    pos_type = country
  ) %>% 
  pivot_longer(cols = c(democratic, republican),
               names_to = "party",
               values_to = "seats") %>% 
    select(pos_type, year, party, seats),
  house_senate_clean_data %>% 
    select(pos_type, year, party, seats)) %>%
  filter(party == "democratic") %>%
  mutate(pos_type = factor(pos_type, levels = c(
    "house",
    "senate",
    top_5_donate_countries
  ))) %>% 
  arrange(pos_type) %>% 
  select(-party)

```

```{r line-plot-by-country, echo = FALSE}
ggplot(top_5_foreign_data_bound, aes(x=year, y=seats, color=pos_type, alpha = pos_type)) +
  geom_line() +
  theme_clean() +
  scale_alpha_manual(values = c(1,1,.3,.3,.3,.3,.3)) +
  theme(axis.text.x = element_text(angle=-60, hjust=0)) +
  labs(title = "Top 5 Foreign Donation Countries and\nCongress Representation Over Time",
       x = "Year",
       y = "Representation (%)",
       color = "Position",
       caption = "OpenSecrets.org (2021)") +
  scale_y_continuous(labels = scales::percent_format(accuracy=1),
                     limits = c(.2, .8)) +
  guides(alpha = "none")
  
```