---
title: "Figures in Appendix C"
author: "Nuo Wen Lei"
date: "8/7/2021"
output: html_document
---



```{r setup, include=FALSE}
library(tidyverse)
library(ggthemes)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r party-donation-clean, echo = FALSE}
foreign_data = read_csv("../data/foreign_pac_data/clean_data.csv")

foreign_clean_data = foreign_data %>% 
  group_by(year) %>% 
  summarize(total = sum(dems_sum) + sum(repubs_sum),
            dem = sum(dems_sum),
            repub = sum(repubs_sum),
            .groups = "drop") %>%
  mutate(dem_percent = dem / total,
         repub_percent = repub / total) %>% 
  pivot_longer(
    cols = c(dem_percent, repub_percent),
    names_to = "party",
    values_to = "amount"
  )
```

```{r load-leadership, echo = FALSE, warning = FALSE, message = FALSE}
leadership_data = read_csv("../data/leadership_pac_data/clean_data.csv")

leadership_clean_data = leadership_data %>% 
  group_by(year) %>% 
  summarize(total = sum(dem) + sum(repub),
            dem = sum(dem),
            repub = sum(repub),
            .groups = "drop") %>%
  mutate(dem_percent = dem / total,
         repub_percent = repub / total) %>% 
  pivot_longer(
    cols = c(dem_percent, repub_percent),
    names_to = "party",
    values_to = "amount"
  )
```

```{r load-industry, echo = FALSE, warning = FALSE, message = FALSE}
industry_data = read_csv("../data/industry_donation_data/clean_data.csv")

industry_clean_data = industry_data %>% 
  group_by(year) %>% 
  summarize(total = sum(dem) + sum(repub),
            dem = sum(dem),
            repub = sum(repub),
            .groups = "drop") %>%
  mutate(dem_percent = dem / total,
         repub_percent = repub / total) %>% 
  pivot_longer(
    cols = c(dem_percent, repub_percent),
    names_to = "party",
    values_to = "amount"
  )
```

```{r load-house_senate, echo = FALSE, warning = FALSE, message = FALSE}
house_senate_data = read_csv("../data/house_senate.csv")

house_senate_clean_data = house_senate_data %>% 
  pivot_longer(cols = -year, names_to = "position", values_to = "seats") %>% 
  mutate(
    party = gsub("\\_.*", "", position),
    pos_type = gsub(".*\\_", "", substr(position, 1, nchar(position)-2))
  ) %>% 
  group_by(pos_type, year) %>% 
  summarize(party = party,
            seat_total = seats,
            seats = seats / sum(seats),
            .groups = "drop")
```

```{r linear-plot-foreign}
cbind_foreign_house = cbind(foreign_clean_data %>%
                              select(-c(year, party)),
                               house_senate_clean_data %>%
                                 filter(pos_type == "house"))
cbind_foreign_senate = cbind(foreign_clean_data %>%
                              select(-c(year, party)),
                               house_senate_clean_data %>%
                                 filter(pos_type == "senate"))

ggplot(data = rbind(cbind_foreign_house, cbind_foreign_senate), mapping = aes(x = amount, y = seats, color = pos_type)) +
  geom_point() +
  labs(title = "Congress Party Distribution over\nForeign PAC Donation Distribution",
       x = "donation amount (%)",
       y = "seats (%)",
       caption = "OpenSecrets (2021)",
       color = "Branch")
```

```{r linear-plot-leadership}
cbind_leadership_house = cbind(leadership_clean_data %>%
                              select(-c(year, party)),
                               house_senate_clean_data %>%
                                 filter(pos_type == "house"))
cbind_leadership_senate = cbind(leadership_clean_data %>%
                              select(-c(year, party)),
                               house_senate_clean_data %>%
                                 filter(pos_type == "senate"))

ggplot(data = rbind(cbind_leadership_house, cbind_leadership_senate), mapping = aes(x = amount, y = seats, color = pos_type)) +
  geom_point() +
  labs(title = "Congress Party Distribution over\nLeadership PAC Donation Distribution",
       x = "donation amount (%)",
       y = "seats (%)",
       caption = "OpenSecrets (2021)",
       color = "Branch")
```

```{r linear-plot-industry}
cbind_industry_house = cbind(industry_clean_data %>%
                              select(-c(year, party)),
                               house_senate_clean_data %>%
                                 filter(pos_type == "house"))
cbind_industry_senate = cbind(industry_clean_data %>%
                              select(-c(year, party)),
                               house_senate_clean_data %>%
                                 filter(pos_type == "senate"))

ggplot(data = rbind(cbind_industry_house, cbind_industry_senate), mapping = aes(x = amount, y = seats, color = pos_type)) +
  geom_point() +
  labs(title = "Congress Party Distribution over\nIndustry PAC Donation Distribution",
       x = "donation amount (%)",
       y = "seats (%)",
       caption = "OpenSecrets (2021)",
       color = "Branch")
```